import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import NavbarSwitcher from "@/components/NavbarSwitcher";
import { NotificationIndicator } from '@/components/layout/NotificationIndicator';
import { NotificationProvider } from '@/context/NotificationContext'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AnonyExchange",
  description: "Generated by AnonyExchange app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <NotificationProvider> 
            <div className="relative">
              <NavbarSwitcher />
              <div className="absolute top-4 right-16 z-50">
                <NotificationIndicator />
              </div>
            </div>
            {children}
            <Toaster />
          </NotificationProvider> 
        </AuthProvider>
      </body>
    </html>
  );
}